### ISSUE TITLE
pagination style problem about bootstrap

### ISSUE THREAD

**Issue by samrayleung** [ratiw/vuetable-2-tutorial#2]
Hey,i have a simple question
```css
<div class="vuetable-pagination ui basic segment grid">
```
,your pagination style is based on semantic-ui,and i use bootstrap,but i could not find the pagination style in [vuetable-example-vueify-bootstrap](https://github.com/ratiw/vuetable-example-vueify-bootstrap)

so,what i get is 
![bootsrtap_pagination](https://cloud.githubusercontent.com/assets/14180681/22007089/29537e44-dcab-11e6-80a8-cfeed6dc4246.png).
i am new to programming,could you give me some tips?thanks

**Comment by ratiw** [comment]
@samrayleung That example is for the first version of Vuetable that uses with Vue 1.x. Vuetable-2 is quite different underneath. I'll see if I can add some more info or even the similar tutorial project for Bootstrap CSS. In the meantime, [this `css` prop](https://github.com/ratiw/vuetable-2/blob/master/src/components/Vuetable.vue#L187) is the one you need to override.

**Comment by samrayleung** [comment]
thank for your reply,i will try to figure it out.
Ps:wait for your bootstrap tutorial

**Comment by ratiw** [comment]
Please see this [repo](https://github.com/ratiw/vuetable-2-tutorial-bootstrap).

**Comment by samrayleung** [comment]
thanks again,i do appreciate your work,thanks @ratiw

**Comment by samrayleung** [comment]
https://github.com/ratiw/vuetable-2-tutorial/doc/README.md this url is not found,something wrong?

**Comment by ratiw** [comment]
Sorry, it should be this one [https://github.com/ratiw/vuetable-2-tutorial/blob/master/doc/README.md](https://github.com/ratiw/vuetable-2-tutorial/blob/master/doc/README.md)

**Comment by samrayleung** [comment]
get it,thanks again for your great  work

**Comment by viewplatgh** [comment]
I got the same problem, I cannot make pagination show correctly. The bootstrap example get compiling error, doesn't show the table at all .

===================

OK, I solved above issue by looking into https://github.com/ratiw/vuetable-2-tutorial-bootstrap, the key point is `:css="css.pagination"`
