### ISSUE TITLE
Filtering does not work

### ISSUE THREAD

**Issue by dukadin** [ratiw/vuetable-2-tutorial#23]
Filter bar events are not triggered by default inside parent component.
I had to do this in order to make it working:

- Register event listeners
```
mounted() {
      this.$events.$on('filter-set', eventData => this.onFilterSet(eventData))
      this.$events.$on('filter-reset', e => this.onFilterReset())
}
```

- Moved event methods to _methods_
```
    onFilterSet (filterText) {
        this.moreParams = {
            'filter': filterText.trim()
        }
        Vue.nextTick( () => this.$refs.vuetable.refresh())},
    onFilterReset () {
        this.moreParams = {}
        Vue.nextTick( () => this.$refs.vuetable.refresh())
    }
```

**Comment by ratiw** [comment]
@dukadin Thanks. This has already been reported in [vuetable-2-tutorial-bootstrap](https://github.com/ratiw/vuetable-2-tutorial-bootstrap/issues/4) and [vuetable-2-tutorial-bulma](https://github.com/ratiw/vuetable-2-tutorial-bulma/pulls). Just so busy that I couldn't find the time to update it. A PR would be nice if you could help.

**Comment by dukadin** [comment]
@ratiw Sure, I submited PR.

**Comment by ratiw** [comment]
@dukadin Thanks, will find time to merge it tonight.
