### ISSUE TITLE
Passing row data to modal window instead of detail row

### ISSUE THREAD

**Issue by sjaakvandenberg** [ratiw/vuetable-2-tutorial#31]
I'm trying to pass row data to a modal window, instead of an added row below the one selected (like in [lesson 12](https://github.com/ratiw/vuetable-2-tutorial/blob/master/doc/lesson-12.md)). I'm using Laravel 5.4 and I have a table of servers.

In my main Vue file, the `onRowClicked` function gets called by use of the `@vuetable:row-clicked` property. I import the `ServerModal` component from `./ServerModal`, which is used in the main Vue file's template as `<server-modal>`.

The modal shows up if I remove `{{ rowData.id }}` from the component, but obviously without row-linked data.

How do I pass row data to a component like is done with `toggleDetailRow()`?

Thanks!

```js
// MyVuetable.vue
<template lang="pug">
  .ui.container
    filter-bar(ref="filterbar")
    vuetable(ref="vuetable"
             v-bind:fields="fields"
             v-bind:css="css.table"
             v-bind:per-page="perPage"
             v-bind:sort-order="sortOrder"
             v-bind:append-params="moreParams"
             @vuetable:pagination-data="onPaginationData"
             @vuetable:row-clicked="onRowClicked"
             pagination-path=""
             api-url="/json")
    .ui.basic.segment.grid
      vuetable-pagination-info(ref="paginationInfo")
      vuetable-pagination(ref="pagination"
                          v-bind:css="css.pagination"
                          v-bind:icons="css.icons"
                          @vuetable-pagination:change-page="onChangePage")
    h4.ui.horizontal.divider.header
      i.server.icon
      | Add
    .ui.basic.segment.grid
      add-server-horizontal
    server-modal
</template>

<script>
...
import ServerModal from './ServerModal'
Vue.component('server-modal', ServerModal)
export default {
  ...
  data() {
    return {
      showModal: false,
      ...
    }
  },
  methods: {
    onRowClicked(data) {
      this.showModal = true
      $('.ui.modal').modal('toggle')
      console.log(`Row with id ${data.id} clicked.`)
    },
    ...
  }
}
</script>
```

```js
// ServerModal.vue
<template lang="pug">
  .ui.modal
    i.close.icon
    .header Header
    .image.content
      .image Image
      .description Description {{ rowData.id }}
    .actions
      .ui.button(@click="$emit('close')") Cancel
      .ui.button OK
</template>

<script>
  export default {
    props: {
      rowData: {
        type: Object,
        required: true
      },
      rowIndex: {
        type: Number
      }
    },
    mounted() {
      console.log(`ServerModal mounted.`)
    }
  }
</script>
```

[Gist](https://gist.github.com/sjaakvandenberg/7efbd497f882f0d6ea405afa98743944) with complete relevant files for reference.

**Comment by ratiw** [comment]
@sjaakvandenberg 

You need to bind `server-modal`'s `row-data` prop to the data you want.

The trick is that you have to define a temp object (e.g. `itemData`) in your main vue instance and you use this temp to bind to `server-modal`. When the `row-clicked` event is detected, you set the temp object value to the pass-in data. The code below might be easier to understand.

```vue
// MyVuetable.vue
<template>
  //...
  <server-modal
    :row-data="itemData"
  ></server-modal>
</template>

<script>
// ...
  data() {
    return {
      //..
      itemData: null
    }
  },
  methods: {
    onRowClicked(data) {
      this.itemData = data
      //...
      this.showModal = true
      $('.ui.modal').modal('toggle')
      console.log(`Row with id ${data.id} clicked.`)
    },
    ...
  }
</script>
```

Just be careful about Semantic-UI's Modal though. Because, by default, it will remove the modal out of its place in the DOM and place it inside the `dimmer`. That means by the time Vue starts compiling your html into Virtual DOM, Vue may not see your modal code. You may need to set `detachable` option to `false` to fix this. `$('.ui.modal').modal({detachable: false})`

**Comment by sjaakvandenberg** [comment]
That helps a lot, thanks!
