### ISSUE TITLE
Error when using axios for Vue.$http

### ISSUE THREAD

**Issue by semir-karic** [ratiw/vuetable-2-tutorial#34]
Since vue-resource is deprecated if you use axios for HTTP requests like
Vue.prototype.$http = axios

you get an error 
`Uncaught TypeError: Cannot set property $http of #<Vue$3> which has only a getter`

Maybe it would be better if it was up to user to chose the Vue $http handler since with the current way there is no possibility of using axios as $http handler replacement

**Comment by ratiw** [comment]
@semir-karic This has been discussed in various places in the issues of main Vuetable-2 repo. Someone has already submitted a PR to replace axios with vue-resource and it has already been incorporated into `develop` branch.

**Comment by semir-karic** [comment]
Found the patch. Thanks and great library by the way.

**Comment by vidyarthitech2tech** [comment]
Hey @semir-karic , How did you fix this? I am getting the same error.

**Comment by semir-karic** [comment]
@vidyarthitech2tech just pull the latest vuetable and check this link https://ratiw.github.io/vuetable-2/#/Vuetable-Properties?id=-http-fetch-v17
You can now use your own axios instance to fetch the data.
