### ISSUE TITLE
how to change api-url from MyVuetable.vue

### ISSUE THREAD

**Issue by rained23** [ratiw/vuetable-2-tutorial#35]
Hi,

I am trying to learn vuetable-2, I followed the tutorial and created the basic MyVuetable.vue.
In my page I have <my-vuetable></my-vuetable> . How can I set api-url from my index.html ?

I tried `<my-vuetable api-url="something"></my-vuetable>` and `<my-vuetable :api-url="something"></my-vuetable>` both didnt work, it only work if I set the api-url from MyVuetable.vue.

Thanks.

**Comment by ratiw** [comment]
@rained23 You will have to define `api-url` as a prop in MyVuetable, then you could pass it in index.html, like so

```vue
// MyVuetable.vue
<template>
  //...
  <vuetable ref="vuetable"
      :api-url="apiUrl"
      //...
  ></vuetable>
</template>

<script>
//...
export default {
  //...
  props: ['apiUrl'],
  data () {
    //...
  }
```
```html
  <my-vuetable
    api-url="...url here..."
  ></my-vuetable>
```

**Comment by rained23** [comment]
Thanks for your help
