### ISSUE TITLE
Checkboxes not responding to events

### ISSUE THREAD

**Issue by dvatp** [ratiw/vuetable-2-tutorial#37]
I have been using Vuetable extensively in a project and it works quite well.  I've used many of its features in several different contexts within the application and am now quite familiar with it and its code.

I had a use case where I wanted to click on the row and have it add the "selected" attribute to the appropriate <tr> tag so the browser would highlight the selected row.  Vuetable doesn't support this at present but it does support the concept of selected rows (via checkbox support) so I figured I'd walk through the checkbox related code and see if I could adapt it to serve this need.  The first step was to add a __checkbox to my fields array. After I rebuilt / reloaded the app the checkbox column appeared with all checkboxes unchecked as expected.

The issue, however, is that clicking on the checkboxes does nothing.  The checkboxes remain unchecked.  Clicking on them does not generate any events that I can see OTHER than row-clicked when I click on a checkbox on one of the rows containing data.  Clicking on the top checkbox in the header generates absolutely no events (not even row-clicked).   This is contrary to what I would expect.  Clicking on the checkbox in the header should call the toggleAllCheckboxes method but my debug in that method clearly indicates it is not being called.  Similarly, clicking on the checkboxes in the table rows containing data does not call toggleCheckbox.

I'm using Chrome 56.0.2924.87 for development.  I tried to go back to Firefox to see if that made any difference but as it turns out the version available to me (45.7.0 ESR) lacks support for prototype.forEach so the checkbox code won't work natively with it and I don't want to add a polyfill at the moment.

The only other thing I can mention is that this particular use case involves the use of a SweetModal dialog (i.e. the Vuetable is displayed in a modal dialog).  I have used regular checkboxes in other SweetModal dialogs without issue so I doubt this is specific to the native checkbox element and/or a browser-specific problem.

Any thoughts on what might be causing the checkbox "changed" or "checked" events to be trapped and not reach the checkboxes?

**Comment by ratiw** [comment]
@dvatp Can you please update to v1.6.0 and try again? Please don't forget to check the [release note](https://github.com/ratiw/vuetable-2/releases/tag/v1.6.0) first. 

Also, clone the Vuetable-2 repo, then `npm install && npm run dev` and test in your browser. You should see that the checkbox is working as expected. So, I think that the problem you mentioned might related to the bugs in previous version of Vuetable. 

However, if the problem still persists, please open an issue in the [Vuetable-2 repo](https://github.com/ratiw/vuetable-2)

**Comment by dvatp** [comment]
FYI, I pulled from source around March 1 so I have the changes up to that point.

I had to modify vuetable to work around the checkbox failures, so it will take time to merge in your changes and test them again to see if 1.6.0 fixes the issue.

**Comment by dvatp** [comment]
Upgraded to 1.6.0 and the problem with checkboxes still exists.

The odd thing is that I have some local modifications that I applied and tested which allow me to click to select a row.  This uses a lot of the existing logic to support row selection by checkbox and when I use my logic to select a row AND I have a checkbox field defined, the checkboxes work. Meaning, they react as expected to the change in the selectedTo array, but clicking on them does not work.

So it appears that the issue is that the click event isn't getting through to the checkbox.  Not sure what is causing this. I don't need checkboxes at the moment and don't have the time to debug further, but may have to revisit in the future.

**Comment by dvatp** [comment]
I'm going to close this issue mostly because it doesn't belong in the tutorial.  I will open a new issue in the future in the vuetable-2 repo if I come up with a solution.
