### ISSUE TITLE
Module not found

### ISSUE THREAD

**Issue by filipeluiz** [ratiw/vuetable-2-tutorial#42]
Hello,

Please help me the error here:

`ERROR in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue
Module not found: Error: Can't resolve './components/MyVuetable' in '/home/filipe/vuetable/src'
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/App.vue 12:0-49
 @ ./src/App.vue
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js`

**Comment by ratiw** [comment]
@filipeluiz Check the webpack configuration or use `vue-cli` to create project as in the [prerequisite](https://github.com/ratiw/vuetable-2-tutorial/wiki/_prerequisite#create-a-tutorial-project-with-vue-cli) lesson.

**Comment by filipeluiz** [comment]
thanks ratiw.
