### ISSUE TITLE
Custom dropdown filters

### ISSUE THREAD

**Issue by cosecantt** [ratiw/vuetable-2-tutorial#51]
I am not quite sure if we can add some custom dropdown filters?

User selects an item from dropdown it just filters based on given dropdown item.  Then when a user searches items it searches among filtered items like given in the example below. Below is implemented in jQuery datatable. Tutorial examples would be great. 
![screenhunter_80 jun 13 09 58](https://user-images.githubusercontent.com/5255217/27061452-04345aa6-501f-11e7-907e-68f09b667b44.jpg)

Thank you again for vuetable. It is very useful!

**Comment by ratiw** [comment]
@cosecantt Yes, you can.

Think about it, the dropdown itself is a predefined set of filters. That means it's just another type of filter that your backend API has to deal with. You just need to make Vuetable sent this filter to your backend via `append-params`.

You should first think about the query string that your backend API will receive and work with.

```
  http://example.com/api/products?group=drink&subgroup=all&filter=co
```
These can be used to program into `apppend-params` prop.

**Comment by cosecantt** [comment]
Ok @ratiw thank you. I definately look into that. Thank you again.

**Comment by chaymag** [comment]
Hello how did you manage to add these filters please ?
