### ISSUE TITLE
How to specify column width?

### ISSUE THREAD

**Issue by zuichune** [ratiw/vuetable-2-tutorial#54]
Hi,
How to specify column width?
How do I change the table style?

**Comment by ratiw** [comment]
See [here](https://github.com/ratiw/vuetable-2/issues/113) for an idea.

**Comment by Iyongbudiarso** [comment]
Halloo,
Thanks @ratiw , vuetable-2 is awesome

I want to question, if I using width 500px, not look like 500px in mobile
` {
          name: 'created_at',
          sortField: 'created_at',
          width: '500px'
},`
Column width is shrink. to small. like above
![screenshot-localhost-8081-2018 03 17-18-36-11](https://user-images.githubusercontent.com/4843505/37554411-0098672e-2a13-11e8-8770-9dcfd2f1ac26.png)

In el-table is look good. if I use width: 500px, exactly width is 500px
![screenshot-localhost-8081-2018 03 17-18-35-38](https://user-images.githubusercontent.com/4843505/37554413-087eb3da-2a13-11e8-9150-1925bd02c0ff.png)

I want to using vuetable-2, but width like el-table. How to get that?

Thank you

**Comment by ratiw** [comment]
@Iyongbudiarso Sorry, I don't understand what you mean. What is el-table? The attached pictures did not really help much. And if it is specific question for vuetable-2, please post it in its [repo](https://github.com/ratiw/vuetable-2/issues).
