### ISSUE TITLE
lesson 12 - Detail row without registering component globally?

### ISSUE THREAD

**Issue by alperencaliskan** [ratiw/vuetable-2-tutorial#58]
Hello, is there any way to pass local imported component to "detail-row-component" without registering component globally as in the lesson?
code from lesson 12
```javascript
<script>
    //...
    import DetailRow from './DetailRow'

    Vue.component('my-detail-row', DetailRow)   // <--- register the component to Vue
    //...

</script>
```

**Comment by ratiw** [comment]
No. But you can use scoped slot instead.

**Comment by alperencaliskan** [comment]
I will look into that. Thank you.

**Comment by alperencaliskan** [comment]
It worked! And with one less component. Thank you.
