### ISSUE TITLE
Could you please add an example that does not use api-url but pass the data from parent component?

### ISSUE THREAD

**Issue by taozhaolib** [ratiw/vuetable-2-tutorial#60]
My data query is complicated so I had to pass down the data from parent component directly to the vuetable. I ran into an error like this:

:data="tableData" :fields="fields" pagination-path="" @vuetable:pagination-data="onPaginationData" >
No relevant data

If I replaced the :data attribute with api-url="http://xxxx" it then worked.

**Comment by ratiw** [comment]
Then, is it possible that your data structure of the `tableData` and the one returning from `http://xxxx` is different?

See this [codepen](https://codepen.io/ratiw/project/editor/DzmJnA) if it helps.

**Comment by taozhaolib** [comment]
Thanks this really helps!

**Comment by apooslr** [comment]
I would also like to pass the table my own data, not something I get form an api, how can I do that?

**Comment by ratiw** [comment]
@AndreaRylander See the link to the codepen above.
