### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by sigfriedCub1990** [ratiw/vuetable-2-tutorial#68]
Hello @ratiw, I would love to collaborate with the community translating the vuetable tutorial to spanish language.

**Comment by ratiw** [comment]
@sigfriedCub1990 That's really great to hear. I'm quite occupied with other work at the moment, but please let me know what you need to get started.

**Comment by sigfriedCub1990** [comment]
Thanks @ratiw, for the quick response :), I'll fork to repository and I'll start to translate the tutorials. I'll keep you informed.

**Comment by sigfriedCub1990** [comment]
Unable to work on this for now.
