### ISSUE TITLE
Style not working on Pagination

### ISSUE THREAD

**Issue by nusendra** [ratiw/vuetable-2-tutorial#73]
![screenshot from 2017-12-13 11-38-57](https://user-images.githubusercontent.com/8466308/33921998-431c81ec-dffa-11e7-8c06-8f206348dad8.png)

I'm using bootstrap 3
How to fix this? Please help me @ratiw 
Thanks :-)

**Comment by nusendra** [comment]
I can solve this by modifying the VuetablePaginationMixin.vue file. I will close this issue if this works.

**Comment by ratiw** [comment]
This [codepen](https://codepen.io/ratiw/pen/GmJayw) might help.

**Comment by nusendra** [comment]
Yeah, problem solved. I modify the css props in  Vuetable.vue and VuetablePaginationMixin.vue
So i can keep clean my js file. Thanks @ratiw 

case closed
