### ISSUE TITLE
we must use the api-url to get data plz ?

### ISSUE THREAD

**Issue by yujunjie0603** [ratiw/vuetable-2-tutorial#77]
is there another way to retrieve the data directe ?

I do not find it practical, if the data is not in good format

**Comment by ratiw** [comment]
@yujunjie0603 Sorry, please explain more. I don't understand what you mean or want to achieve.

**Comment by yujunjie0603** [comment]
sorry, I means that how to use :api-mode="false", I had found your example !

Thanks a lot !
