### ISSUE TITLE
How to use `transform()` hook to transform pagination object.

### ISSUE THREAD

**Issue by Mahmoudz** [ratiw/vuetable-2-tutorial#9]
I'm trying to use `vuetable-pagination` but I was never able to see that pagination generated on the view. I assume it's because my pagination object has different format than what this component can understand. In your docs you mention use `transform()`. Can show me an example please, I'm new to VueJS:

My current Pagination looks like this, due to the Dingo API package and the fractal transformer:

```
"meta":{"pagination":{"total":15,"count":10,"per_page":10,"current_page":1,"total_pages":2,"links":{"next":"http:\/\/api.whatever.dev\/admins?sort=&per_page=5&page=2"}}}
```

What is the appropriate way to convert it to:

```
  "total": 200,
  "per_page": 15,
  "current_page": 1,
  "last_page": 14,
  "next_page_url": "http://vuetable.ratiw.net/api/users?page=2",
  "prev_page_url": null,
  "from": 1,
  "to": 15,
```

**Comment by ratiw** [comment]
@Mahmoudz Sorry, couldn't find time to document it or add this to the tutorial. 

Basically, you define a `transform` function in the parent instance of Vuetable, it will call your `transform` function automatically. Inside the `transform` function, you just loop to create the new data (together with the pagination info) and return that transformed data. You can see the example [here](https://github.com/ratiw/vuetable-2/blob/master/src/main.js#L152-L181). Do not worry about the transformation time, it should be very quick as you're working with a very small chuck of data.

Since your pagination information lives inside `meta.pagination` object, it would be something like this. Please note that I haven't tested this. 

```javascript
transform: function(data) {
      let transformed = {}
      let pg = data.meta.pagination

      transformed.pagination = {
        total: pg.total,
        per_page: pg.per_page,
        current_page: pg.current_page,
        last_page: pg.total_page,
        next_page_url: pg.links.next ? pg.links.next : null,
        prev_page_url: pg.links.prev ? pg.links.prev : null,
        from: (pg.current_page -1) * pg.per_page +1,
        to: (pg.current_page -1) * pg.per_page + pg.count
      }

      transformed.data = []
      data = data.data
      for (let i = 0; i < data.length; i++) {
        transformed['data'].push({
          id: data[i].id,
          name: data[i].name,
          nickname: data[i].nickname,
          email: data[i].email,
          age: data[i].age,
          birthdate: data[i].birthdate,
          gender: data[i].gender,
          address: data[i].address.line1 + ' ' + data[i].address.line2 + ' ' + data[i].address.zipcode
        })
      }

      return transformed
    },
```

The data returned from the above transformation will in the `data` array and the `pagination` will be  in the `pagination` object, so you have to set the `data-path` and `pagination-path` props accordingly. Let me know if you get stuck on that.

**Comment by lmj0011** [comment]
>so you have to set the data-path and pagination-path props accordingly. 

example:
https://github.com/ratiw/vuetable-2/blob/master/index.html#L103

I assume `data-path` is left out because the path for it is already correct
(ie. `data-path="data"` )

**Comment by ratiw** [comment]
@lmj0011 Yes, you're correct.

**Comment by anit05** [comment]
@ratiw I have my API returning data in different format. So i used transformation.But pagination is not working with transformed data.

However, if i try example where transformation is not required , pagination works fine.

I am not getting what i am missing

This is my transformed function (for testing):


  transform: function (dataObject) {


            var transformed = {}
            transformed.links = {}
            transformed.links.pagination = {
                total: 200,
                per_page: 1,
                current_page: 1,
                last_page: 14,
                next_page_url: "https://vuetable.ratiw.net/api/users?page=2",
                prev_page_url: null,
                from: 1,
                to: 1,
            }
            console.log(transformed);
            transformed.data = []
          var  data = [
{
    "id": 1,
    "name": "Noelia O'Kon",
    "nickname": "asperiores",
    "email": "otho.smitham@example.com",
    "birthdate": "1978-06-28 00:00:00",
    "gender": "F",
    "salary": "13098.00",
    "group_id": 2,
    "created_at": "2017-01-01 07:21:10",
    "updated_at": "2017-01-01 07:21:10",
    "age": 39,
    "group": {
        "id": 2,
        "name": "Exec",
        "description": "Executives"
    },
    "address": {
        "id": 1,
        "user_id": 1,
        "line1": "0888 Aniyah Locks\nLake Bridie, NJ 51086",
        "line2": "Cayman Islands",
        "zipcode": "92991-2805",
        "mobile": "1-742-816-9238x848",
        "fax": "(484)438-4697x8638"
    }
},


            ];
            transformed.data =  data
     


            return transformed;
        },


And this is my vuetable :

   <div id="app">               
                    <div class="ui container">
                        <vuetable ref="vuetable"
                                  :api-url="apiUrl"
                                  :fields="fields"
                                  data-path="data"
                                  pagination-path="pagination"
                                  :css="theme"
                                  :per-page="perPage"
                                 :query-params="queryParams"
                                  @@vuetable:pagination-data="onPaginationData">
                            <template slot="actions" scope="props">
                                <div class="table-button-container">
                                    <button class="ui button" ><i class="fa fa-edit"></i> Edit</button>&nbsp;&nbsp;
                                    <button class="ui basic red button" ><i class="fa fa-remove"></i> Delete</button>&nbsp;&nbsp;
                                </div>
                            </template>
                        </vuetable>
                        <vuetable-pagination ref="pagination"
                                             @@vuetable-pagination:change-page="onChangePage"></vuetable-pagination>
                   
                </div>


please have a look

**Comment by drascom** [comment]
hi ratiw i'm sending url's as props for different url and getting response from different tables at api mode.All functions working very good. But have to manipulate some cell data before rendering to table .
My structure is like 
parent_1 => dataTable comp.=>vuetable comp
parent_2 =>dataTable comp. =>vuetable comp.
...
...
as i understand i need to use transform at my 2nd component 
how can i use transforming data at my parent component

**Comment by gassio** [comment]
> 
> Basically, you define a `transform` function in the parent instance of Vuetable

@ratiw I cannot understand what do you mean when saying "parent instance of Vuetable". Could you please tell me where to put the transform function?

**Comment by ratiw** [comment]
Please see this https://www.vuetable.com/guide/data-transformation.html

**Comment by gassio** [comment]
@ratiw Thank you for the quick response. I 've seen already this page https://www.vuetable.com/guide/data-transformation.html.
In my case, I use single file components. And I cannot understand why the transform function does not work. Here is my code:

``` js
// SomeComponent.vue
<script>
methods: {
    transform(data) {
      console.log('transform()')
      return data
    }
}
</script>

<template>
    <vuetable ref="vuetable" :api-url="'...'" fields="..." transform="transform"></vuetable>
</template>
```
